# -- Site Settings -----------------------------------------------------------
title: "天算AI" # 网站标题 (Cayman 会用)
description: "天算AI - AI科技博主 | AI科技研发 | 最新AI资讯影视化报道" # 网站描述 (Cayman 会用)
url: "https://jinvbar.github.io" # 网站的根 URL
baseurl: "/tsai" # 仓库名称
repository: "jinvbar/tsai" # GitHub 仓库路径 (布局文件可能会用到)

# -- Theme Settings ----------------------------------------------------------
theme: jekyll-theme-cayman # <--- 明确使用 Cayman 主题

# -- Build Settings ----------------------------------------------------------
markdown: kramdown
highlighter: rouge

# -- Plugins (只保留最基础、GitHub Pages 默认支持的) --------------------
plugins:
  - jekyll-sitemap # 生成 sitemap.xml (推荐保留)
  - jekyll-feed   # 生成 Atom feed (推荐保留)
# - jekyll-seo-tag # Cayman 主题通常自己处理 SEO，可以先不用
# - jekyll-paginate # Cayman 主题默认分页支持不好，移除
# - jekyll-gist
# - jekyll-include-cache # Cayman 不需要

# --- Exclude from processing (可选，保持默认通常即可) -------------------
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
