# -- Site Settings -----------------------------------------------------------
title: "天算AI"
description: "天算AI - AI科技博主 | AI科技研发 | 最新AI资讯影视化报道"
url: "https://jinv2.github.io"
baseurl: ""
repository: "jinv2/jinv2.github.io"

# -- Theme Settings ----------------------------------------------------------
theme: jekyll-theme-cayman # 确认主题是否仍为 Cayman

# -- Build Settings ----------------------------------------------------------
markdown: kramdown
highlighter: rouge
future: true # 如果不需要显示未来日期的文章，设为 false 或删除

# -- Plugins -----------------------------------------------------------------
plugins:
  - jekyll-sitemap
  - jekyll-feed
  # - jekyll-seo-tag # 如果 Cayman 主题已处理SEO，则可注释；否则取消注释

# --- Exclude from processing (建议保留这些默认排除项) -------------
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md # 通常README.md是给仓库看的，不是博客页面
  # - LICENSE.txt # 如果有，也可以排除
  # - .jekyll-cache/ # Jekyll的缓存目录
  # - .sass-cache/ # Sass的缓存目录
  # - .git/ # Git目录
  # - .gitignore # Git忽略文件
